services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  OliverKroener\OkCookiebotCookieConsent\:
    resource: '../Classes/*'

  OliverKroener\OkCookiebotCookieConsent\Rendering\CookiebotScriptRenderer:
    public: true
